In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('inaianPMlist.xlsx')

In [3]:
df.head()

   S.No              Prime Minister       Start Period          End Period
0     1     Pandit Jawaharlal Nehru      15th Aug 1947       27th May 1964
1     2  Gulzarilal Nanda (interim)      27th May 1964        9th Jun 1964
2     3         Lal Bahadur Shastri     9th June 1964    11th January 1966
3     4            Gulzarilal Nanda  11th January 1966   24th January 1966
4     5               Indira Gandhi  24th January 1966     24th March 1977

In [4]:
# df['Start Period'] = df['Start Period'].str.strip()

# df['Start Period'] = pd.to_datetime(
#     df['Start Period'],
#     format='mixed'
# )

In [5]:
for col in ['Start Period', 'End Period']:
    df[col] = df[col].str.strip()
    df[col] = pd.to_datetime(df[col], format='mixed')

In [6]:
print(df[['Start Period', 'End Period']].dtypes)

Start Period    datetime64[ns]
End Period      datetime64[ns]
dtype: object

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   S.No            18 non-null     int64
 1   Prime Minister  18 non-null     object
 2   Start Period    18 non-null     datetime64[ns]
 3   End Period      17 non-null     datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(1)
memory usage: 708.0+ bytes

In [8]:
df = df.set_index('S.No')

In [9]:
df.head()

                  Prime Minister Start Period End Period
S.No
1        Pandit Jawaharlal Nehru   1947-08-15 1964-05-27
2     Gulzarilal Nanda (interim)   1964-05-27 1964-06-09
3            Lal Bahadur Shastri   1964-06-09 1966-01-11
4               Gulzarilal Nanda   1966-01-11 1966-01-24
5                  Indira Gandhi   1966-01-24 1977-03-24

In [10]:
df.tail()

            Prime Minister Start Period End Period
S.No
14         H. D Deve Gowda   1996-06-01 1997-04-21
15      Inder Kumar Gujral   1997-04-21 1998-03-18
16    Atal Bihari Vajpayee   1998-03-18 2004-05-22
17       Dr Manmohan Singh   2004-05-22 2014-05-17
18           Narendra Modi   2014-05-26        NaT

In [11]:
df.columns.to_list()

['Prime Minister', 'Start Period', 'End Period']

1. How many Prime Ministers are present in the dataset?

In [12]:
count = df['Prime Minister'].nunique()

In [13]:
count

16

2. How many total records are in the dataset?

In [14]:
total_records = df.shape[0]

In [15]:
total_records

18

3. How many columns are present in the dataset?

In [16]:
total_columns = df.shape[1]

In [17]:
total_columns

3

4. Find the names of all unique Prime Ministers.

In [18]:
prime_ministers = df['Prime Minister'].unique()

In [19]:
prime_ministers

array(['Pandit Jawaharlal Nehru', 'Gulzarilal Nanda (interim)',
       'Lal Bahadur Shastri', 'Gulzarilal Nanda', 'Indira Gandhi',
       'Morarji Desai', 'Charan Singh', 'Rajiv Gandhi',
       'Vishwa Pratap Singh', 'Chandra Shekhar', 'P. V Narasimha Rao',
       'Atal Bihari Vajpayee', 'H. D Deve Gowda', 'Inder Kumar Gujral',
       'Dr Manmohan Singh', 'Narendra Modi'], dtype=object)

5. Count how many times each Prime Minister appears.

In [20]:
pm_counts = df['Prime Minister'].value_counts()

In [21]:
pm_counts

Prime Minister
Indira Gandhi                 2
Atal Bihari Vajpayee          2
Pandit Jawaharlal Nehru       1
Gulzarilal Nanda (interim)    1
Lal Bahadur Shastri           1
Gulzarilal Nanda              1
Morarji Desai                 1
Charan Singh                  1
Rajiv Gandhi                  1
Vishwa Pratap Singh           1
Chandra Shekhar               1
P. V Narasimha Rao            1
H. D Deve Gowda               1
Inder Kumar Gujral            1
Dr Manmohan Singh             1
Narendra Modi                 1
Name: count, dtype: int64

6. Check whether there are missing values in the dataset.

In [22]:
missing_values = df.isnull().sum()

In [23]:
missing_values

Prime Minister    0
Start Period      0
End Period        1
dtype: int64

7. Find the records where the End Period is missing.

In [24]:
result = df[df['End Period'].isna()]

In [25]:
result

     Prime Minister Start Period End Period
S.No
18    Narendra Modi   2014-05-26        NaT

8. Find the Prime Minister with the earliest Start Period.

In [26]:
idx = df['Start Period'].idxmin()

In [27]:
df.loc[idx]

Prime Minister    Pandit Jawaharlal Nehru
Start Period          1947-08-15 00:00:00
End Period            1964-05-27 00:00:00
Name: 1, dtype: object

9. Find the Prime Minister with the latest Start Period.

In [28]:
idx = df['Start Period'].idxmax()

In [29]:
df.loc[idx]

Prime Minister          Narendra Modi
Start Period      2014-05-26 00:00:00
End Period                        NaT
Name: 18, dtype: object

10. Find the earliest Start Period in the dataset.

In [30]:
earliest = df['Start Period'].min()

In [31]:
earliest

Timestamp('1947-08-15 00:00:00')

11. Find the latest End Period in the dataset.

In [32]:
latest = df['End Period'].max()

In [33]:
latest

Timestamp('2014-05-17 00:00:00')

12. Calculate the tenure of each Prime Minister in days.

In [34]:
df['Tenure Days'] = (
    df['End Period'] - df['Start Period']
).dt.days

In [35]:
df[['Prime Minister', 'Tenure Days']]

                  Prime Minister  Tenure Days
S.No
1        Pandit Jawaharlal Nehru       6130.0
2     Gulzarilal Nanda (interim)         13.0
3            Lal Bahadur Shastri        581.0
4               Gulzarilal Nanda         13.0
5                  Indira Gandhi       4077.0
6                  Morarji Desai        856.0
7                   Charan Singh        170.0
8                  Indira Gandhi       1752.0
9                   Rajiv Gandhi       1858.0
10           Vishwa Pratap Singh        343.0
11               Chandra Shekhar        223.0
12            P. V Narasimha Rao       1791.0
13          Atal Bihari Vajpayee         16.0
14               H. D Deve Gowda        324.0
15            Inder Kumar Gujral        331.0
16          Atal Bihari Vajpayee       2257.0
17             Dr Manmohan Singh       3647.0
18                 Narendra Modi          NaN

13. Calculate the tenure of each Prime Minister in years.

In [36]:
df['Tenure Years'] = (
    (df['End Period'] - df['Start Period']).dt.days / 365.25
)

In [37]:
df[['Prime Minister', 'Tenure Years']].round(2)

                  Prime Minister  Tenure Years
S.No
1        Pandit Jawaharlal Nehru         16.78
2     Gulzarilal Nanda (interim)          0.04
3            Lal Bahadur Shastri          1.59
4               Gulzarilal Nanda          0.04
5                  Indira Gandhi         11.16
6                  Morarji Desai          2.34
7                   Charan Singh          0.47
8                  Indira Gandhi          4.80
9                   Rajiv Gandhi          5.09
10           Vishwa Pratap Singh          0.94
11               Chandra Shekhar          0.61
12            P. V Narasimha Rao          4.90
13          Atal Bihari Vajpayee          0.04
14               H. D Deve Gowda          0.89
15            Inder Kumar Gujral          0.91
16          Atal Bihari Vajpayee          6.18
17             Dr Manmohan Singh          9.98
18                 Narendra Modi           NaN

14. Find the Prime Minister with the longest tenure.

In [38]:
df['Tenure Days'] = (
    df['End Period'] - df['Start Period']
).dt.days

idx = df['Tenure Days'].idxmax()

In [39]:
df.loc[idx]

Prime Minister    Pandit Jawaharlal Nehru
Start Period          1947-08-15 00:00:00
End Period            1964-05-27 00:00:00
Tenure Days                        6130.0
Tenure Years                    16.783025
Name: 1, dtype: object

15. Find the Prime Minister with the shortest tenure.

In [40]:
df['Tenure Days'] = (
    df['End Period'] - df['Start Period']
).dt.days

idx = df['Tenure Days'].idxmin()

In [41]:
df.loc[idx]

Prime Minister    Gulzarilal Nanda (interim)
Start Period             1964-05-27 00:00:00
End Period               1964-06-09 00:00:00
Tenure Days                             13.0
Tenure Years                        0.035592
Name: 2, dtype: object

16. Sort Prime Ministers by Start Period from oldest to newest.

In [44]:
result = df.sort_values(
    by='Start Period',
    ascending=True
)

In [45]:
result

,Prime Minister,Start Period,End Period,Tenure Days,Tenure Years
S.No,,,,,
1,Pandit Jawaharlal Nehru,1947-08-15,1964-05-27,6130.0,16.783025
2,Gulzarilal Nanda (interim),1964-05-27,1964-06-09,13.0,0.035592
3,Lal Bahadur Shastri,1964-06-09,1966-01-11,581.0,1.590691
4,Gulzarilal Nanda,1966-01-11,1966-01-24,13.0,0.035592
5,Indira Gandhi,1966-01-24,1977-03-24,4077.0,11.162218
6,Morarji Desai,1977-03-24,1979-07-28,856.0,2.343600
7,Charan Singh,1979-07-28,1980-01-14,170.0,0.465435
8,Indira Gandhi,1980-01-14,1984-10-31,1752.0,4.796715
9,Rajiv Gandhi,1984-10-31,1989-12-02,1858.0,5.086927
10,Vishwa Pratap Singh,1989-12-02,1990-11-10,343.0,0.939083
11,Chandra Shekhar,1990-11-10,1991-06-21,223.0,0.610541
12,P. V Narasimha Rao,1991-06-21,1996-05-16,1791.0,4.903491
13,Atal Bihari Vajpayee,1996-05-16,1996-06-01,16.0,0.043806
14,H. D Deve Gowda,1996-06-01,1997-04-21,324.0,0.887064
15,Inder Kumar Gujral,1997-04-21,1998-03-18,331.0,0.906229
16,Atal Bihari Vajpayee,1998-03-18,2004-05-22,2257.0,6.179329
17,Dr Manmohan Singh,2004-05-22,2014-05-17,3647.0,9.984942
18,Narendra Modi,2014-05-26,NaT,NaN,NaN

17. Sort Prime Ministers by End Period from newest to oldest.

In [46]:
result = df.sort_values(
    by='End Period',
    ascending=False
)

In [47]:
result

,Prime Minister,Start Period,End Period,Tenure Days,Tenure Years
S.No,,,,,
17,Dr Manmohan Singh,2004-05-22,2014-05-17,3647.0,9.984942
16,Atal Bihari Vajpayee,1998-03-18,2004-05-22,2257.0,6.179329
15,Inder Kumar Gujral,1997-04-21,1998-03-18,331.0,0.906229
14,H. D Deve Gowda,1996-06-01,1997-04-21,324.0,0.887064
13,Atal Bihari Vajpayee,1996-05-16,1996-06-01,16.0,0.043806
12,P. V Narasimha Rao,1991-06-21,1996-05-16,1791.0,4.903491
11,Chandra Shekhar,1990-11-10,1991-06-21,223.0,0.610541
10,Vishwa Pratap Singh,1989-12-02,1990-11-10,343.0,0.939083
9,Rajiv Gandhi,1984-10-31,1989-12-02,1858.0,5.086927
8,Indira Gandhi,1980-01-14,1984-10-31,1752.0,4.796715
7,Charan Singh,1979-07-28,1980-01-14,170.0,0.465435
6,Morarji Desai,1977-03-24,1979-07-28,856.0,2.343600
5,Indira Gandhi,1966-01-24,1977-03-24,4077.0,11.162218
4,Gulzarilal Nanda,1966-01-11,1966-01-24,13.0,0.035592
3,Lal Bahadur Shastri,1964-06-09,1966-01-11,581.0,1.590691
2,Gulzarilal Nanda (interim),1964-05-27,1964-06-09,13.0,0.035592
1,Pandit Jawaharlal Nehru,1947-08-15,1964-05-27,6130.0,16.783025
18,Narendra Modi,2014-05-26,NaT,NaN,NaN

18. Find Prime Ministers who served for more than 5 years.

In [49]:
df['Tenure Years'] = (
    (df['End Period'] - df['Start Period']).dt.days / 365.25
)

result = df[df['Tenure Years'] > 5]

In [50]:
result[['Prime Minister', 'Tenure Years']]

               Prime Minister  Tenure Years
S.No
1     Pandit Jawaharlal Nehru     16.783025
5               Indira Gandhi     11.162218
9                Rajiv Gandhi      5.086927
16       Atal Bihari Vajpayee      6.179329
17          Dr Manmohan Singh      9.984942

19. Find the average tenure of Prime Ministers.

In [51]:
df['Tenure Years'] = (
    (df['End Period'] - df['Start Period']).dt.days / 365.25
)

average_tenure = df['Tenure Years'].mean()

In [52]:
average_tenure

np.float64(3.9267222289326402)

20. Create a final summary showing Prime Minister, Start Period,
End Period, and Tenure Years.

In [53]:
df['Tenure Years'] = (
    (df['End Period'] - df['Start Period']).dt.days / 365.25
)

summary = df[
    ['Prime Minister', 'Start Period', 'End Period', 'Tenure Years']
]

In [54]:
summary

                  Prime Minister Start Period End Period  Tenure Years
S.No
1        Pandit Jawaharlal Nehru   1947-08-15 1964-05-27     16.783025
2     Gulzarilal Nanda (interim)   1964-05-27 1964-06-09      0.035592
3            Lal Bahadur Shastri   1964-06-09 1966-01-11      1.590691
4               Gulzarilal Nanda   1966-01-11 1966-01-24      0.035592
5                  Indira Gandhi   1966-01-24 1977-03-24     11.162218
6                  Morarji Desai   1977-03-24 1979-07-28      2.343600
7                   Charan Singh   1979-07-28 1980-01-14      0.465435
8                  Indira Gandhi   1980-01-14 1984-10-31      4.796715
9                   Rajiv Gandhi   1984-10-31 1989-12-02      5.086927
10           Vishwa Pratap Singh   1989-12-02 1990-11-10      0.939083
11               Chandra Shekhar   1990-11-10 1991-06-21      0.610541
12            P. V Narasimha Rao   1991-06-21 1996-05-16      4.903491
13          Atal Bihari Vajpayee   1996-05-16 1996-06-01      0.043806
14               H. D Deve Gowda   1996-06-01 1997-04-21      0.887064
15            Inder Kumar Gujral   1997-04-21 1998-03-18      0.906229
16          Atal Bihari Vajpayee   1998-03-18 2004-05-22      6.179329
17             Dr Manmohan Singh   2004-05-22 2014-05-17      9.984942
18                 Narendra Modi   2014-05-26        NaT           NaN